/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Admin
 * Created: 15-mag-2016
 */


CREATE TABLE oggetto(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
categoria VARCHAR(128),
nome VARCHAR(128),
url VARCHAR(128),
descrizione VARCHAR(128),
prezzo DOUBLE PRECISION,
quantita INTEGER,
venditore_id INTEGER,
FOREIGN KEY (venditore_id) REFERENCES venditore(id)

);