/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Admin
 * Created: 23-mag-2016
 */

CREATE TABLE cliente(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(128),
cognome VARCHAR(128),
username VARCHAR(128),
password VARCHAR(128),
tipo VARCHAR(128),
conto DOUBLE PRECISION
);

CREATE TABLE venditore(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(128),
cognome VARCHAR(128),
username VARCHAR(128),
password VARCHAR(128),
tipo VARCHAR(128),
conto DOUBLE PRECISION
);

CREATE TABLE oggetto(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
categoria VARCHAR(128),
nome VARCHAR(128),
url VARCHAR(128),
descrizione VARCHAR(128),
prezzo DOUBLE PRECISION,
quantita INTEGER,
venditore_id INTEGER,
FOREIGN KEY (venditore_id) REFERENCES venditore(id)

);